export default {
  clear: '清空文档',
  image: '单图上传',
  script: {
    sub: '上标',
    super: '下标',
  },
  'select-all': '全选',
  undo: '撤销',
  redo: '重做',
  'formula-editor': '新建公式(ctrl+m)',
  underline: {
    normal: '字体下划线',
    wavy: '下划线-曲线',
  },
  svg2latex: 'SVG 转为 LaTex',
  latex2svg: 'LaTex 转为 SVG(ctrl+b)',
  'fill-blank-underline': '标准下划线',
  pinyin: '插入拼音',
  align: {
    left: '居左对齐',
    center: '居中对齐',
    right: '居右对齐',
  },
  strike: '删除线',
  italic: '斜体',
  dotted: '加点字',
  'fill-blank-brackets': '标准括号',
  'text-indent': '首行缩进',
  'fill-blank-order': '插入空格',
};
